/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: antonmoek (https://sketchfab.com/antonmoek)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cartoon-lowpoly-small-city-free-pack-edd1c604e1e045a0a2a552ddd9a293e6
title: Cartoon Lowpoly Small City Free Pack
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    CAR_03_1_World_ap_0: THREE.Mesh
    CAR_03_World_ap_0: THREE.Mesh
    Car_04_World_ap_0: THREE.Mesh
    CAR_03_2_World_ap_0: THREE.Mesh
    Car_04_1_World_ap_0: THREE.Mesh
    Car_04_2_World_ap_0: THREE.Mesh
    Car_04_3_World_ap_0: THREE.Mesh
    Car_04_4_World_ap_0: THREE.Mesh
    Car_08_4_World_ap8_0: THREE.Mesh
    Car_08_3_World_ap9_0: THREE.Mesh
    Car_04_1_2_World_ap_0: THREE.Mesh
    Car_08_2_World_ap11_0: THREE.Mesh
    CAR_03_1_2_World_ap_0: THREE.Mesh
    CAR_03_2_2_World_ap_0: THREE.Mesh
    Car_04_2_2_World_ap_0: THREE.Mesh
    Car_08_1_World_ap15_0: THREE.Mesh
    Car_08_World_ap16_0: THREE.Mesh
    Car_08_5_World_ap17_0: THREE.Mesh
    CAR_03_2_3_World_ap_0: THREE.Mesh
    Car_08_6_World_ap19_0: THREE.Mesh
    CAR_03_3_World_ap_0: THREE.Mesh
    traffic_light_World_ap_0: THREE.Mesh
    Light_3_World_ap_0: THREE.Mesh
    Light_2_World_ap_0: THREE.Mesh
    Light_1_World_ap_0: THREE.Mesh
    Light_World_ap_0: THREE.Mesh
    traffic_light_1_World_ap_0: THREE.Mesh
    traffic_light_2_World_ap_0: THREE.Mesh
    Floor_4_World_ap_0: THREE.Mesh
    Floor_World_ap_0: THREE.Mesh
    Bed_World_ap_0: THREE.Mesh
    Bushes_3_World_ap_0: THREE.Mesh
    Bed_2_World_ap_0: THREE.Mesh
    Bushes_3_2_World_ap_0: THREE.Mesh
    House_World_ap_0: THREE.Mesh
    Bench_1_World_ap_0: THREE.Mesh
    House_2_World_ap_0: THREE.Mesh
    Light_3_2_World_ap_0: THREE.Mesh
    Light_2_2_World_ap_0: THREE.Mesh
    Light_1_2_World_ap_0: THREE.Mesh
    Light_2_3_World_ap_0: THREE.Mesh
    Floor_4_2_World_ap_0: THREE.Mesh
    Floor_2_World_ap_0: THREE.Mesh
    Firtree_47_World_ap_0: THREE.Mesh
    Firtree_3_World_ap_0: THREE.Mesh
    Firtree_2_World_ap_0: THREE.Mesh
    Firtree_1_World_ap_0: THREE.Mesh
    Firtree_World_ap_0: THREE.Mesh
    Cube_7_World_ap_0: THREE.Mesh
    Firtree_4_World_ap_0: THREE.Mesh
    Bench_World_ap_0: THREE.Mesh
    Muff_1_World_ap_0: THREE.Mesh
    Muff_World_ap_0: THREE.Mesh
    Light_3_3_World_ap_0: THREE.Mesh
    Light_2_4_World_ap_0: THREE.Mesh
    Light_1_3_World_ap_0: THREE.Mesh
    Light_3_4_World_ap_0: THREE.Mesh
    Light_4_World_ap_0: THREE.Mesh
    Light_5_World_ap_0: THREE.Mesh
    Floor_4_3_World_ap_0: THREE.Mesh
    Floor_3_World_ap_0: THREE.Mesh
    Firtree_47_2_World_ap_0: THREE.Mesh
    Firtree_3_2_World_ap_0: THREE.Mesh
    Firtree_2_2_World_ap_0: THREE.Mesh
    Firtree_1_2_World_ap_0: THREE.Mesh
    Firtree_2_3_World_ap_0: THREE.Mesh
    Cube_7_2_World_ap_0: THREE.Mesh
    Firtree_4_2_World_ap_0: THREE.Mesh
    Bench_2_World_ap_0: THREE.Mesh
    Behch_World_ap_0: THREE.Mesh
    House_3_World_ap_0: THREE.Mesh
    Shop_World_ap_0: THREE.Mesh
    Trash_World_ap_0: THREE.Mesh
    Trash_2_World_ap_0: THREE.Mesh
    Light_3_5_World_ap_0: THREE.Mesh
    Light_2_5_World_ap_0: THREE.Mesh
    Light_4_2_World_ap_0: THREE.Mesh
    Floor_4_4_World_ap_0: THREE.Mesh
    Floor_4_5_World_ap_0: THREE.Mesh
    Bed_3_World_ap_0: THREE.Mesh
    Bushes_15_World_ap_0: THREE.Mesh
    Bushes_2_World_ap_0: THREE.Mesh
    Bushes_2_2_World_ap_0: THREE.Mesh
    Tree_1_World_ap_0: THREE.Mesh
    Tree_2_World_ap_0: THREE.Mesh
    Tree_3_World_ap_0: THREE.Mesh
    Bed_4_World_ap_0: THREE.Mesh
    Bushes_15_2_World_ap_0: THREE.Mesh
    Bushes_2_3_World_ap_0: THREE.Mesh
    Bushes_4_World_ap_0: THREE.Mesh
    Tree_1_2_World_ap_0: THREE.Mesh
    Tree_2_2_World_ap_0: THREE.Mesh
    Tree_3_2_World_ap_0: THREE.Mesh
    traffic_light_2_2_World_ap_0: THREE.Mesh
    traffic_light_1_2_World_ap_0: THREE.Mesh
    traffic_light_2_3_World_ap_0: THREE.Mesh
    ROAD_Lines_12_World_ap_0: THREE.Mesh
    ROAD_World_ap_0: THREE.Mesh
    Floor_6_World_ap_0: THREE.Mesh
  }
  materials: {
    World_ap: THREE.MeshStandardMaterial
    ['World_ap.8']: THREE.MeshStandardMaterial
    ['World_ap.9']: THREE.MeshStandardMaterial
    ['World_ap.11']: THREE.MeshStandardMaterial
    ['World_ap.15']: THREE.MeshStandardMaterial
    ['World_ap.16']: THREE.MeshStandardMaterial
    ['World_ap.17']: THREE.MeshStandardMaterial
    ['World_ap.19']: THREE.MeshStandardMaterial
  }
}

export function SmallCityModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('small_city/scene.gltf') as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-397.59, -77.16, -513.34]} rotation={[Math.PI, 0.89, 2.54]} />
          <group rotation={[Math.PI, -0.86, Math.PI]}>
            <group position={[-130.85, -77.16, 635.99]}>
              <group position={[4997.2, 97109.09, 113113.2]} rotation={[-0.71, 0.03, 0.03]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                  <group rotation={[Math.PI / 2, 0, 0]} />
                </group>
                <group rotation={[Math.PI / 2, 0, 0]}>
                  <group rotation={[Math.PI / 2, 0, 0]} />
                </group>
              </group>
              <group position={[-2377.08, 1095, 2809.78]} rotation={[-0.37, -0.67, -0.24]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                  <group rotation={[Math.PI / 2, 0, 0]} />
                </group>
              </group>
            </group>
            <group rotation={[Math.PI / 2, 0, 0]}>
              <group rotation={[Math.PI / 2, 0, 0]} />
            </group>
          </group>
          <group position={[-369.07, -90.7, -920.16]}>
            <group position={[22.13, 14.66, -475.07]} rotation={[-Math.PI, 0.73, Math.PI]} scale={1.5}>
              <mesh geometry={nodes.CAR_03_1_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-281.16, 14.66, 108.45]} rotation={[Math.PI, 1.54, -Math.PI]} scale={1.5}>
              <mesh geometry={nodes.CAR_03_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-302.7, 21.45, 233.84]} rotation={[0, 1.57, 0]} scale={1.5}>
              <mesh geometry={nodes.Car_04_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-478.53, 14.66, 1463.24]} rotation={[Math.PI, -1.46, Math.PI]} scale={1.5}>
              <mesh geometry={nodes.CAR_03_2_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-445.67, 21.45, -438.27]} rotation={[0, 1.57, 0]} scale={1.5}>
              <mesh geometry={nodes.Car_04_1_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-1097.65, 21.45, 1123.55]} rotation={[Math.PI, -0.01, Math.PI]} scale={1.5}>
              <mesh geometry={nodes.Car_04_2_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[449.95, 21.45, 544.78]} rotation={[Math.PI, -1.57, Math.PI]} scale={1.5}>
              <mesh geometry={nodes.Car_04_3_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[780.42, 21.45, -35.69]} rotation={[Math.PI, 0, -Math.PI]} scale={1.5}>
              <mesh geometry={nodes.Car_04_4_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[938.82, -12.94, 754.09]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.5}>
              <mesh geometry={nodes.Car_08_4_World_ap8_0.geometry} material={materials['World_ap.8']} />
            </group>
            <group position={[187.87, -12.94, 1351.54]} rotation={[Math.PI / 2, 0, 3.1]} scale={1.5}>
              <mesh geometry={nodes.Car_08_3_World_ap9_0.geometry} material={materials['World_ap.9']} />
            </group>
            <group position={[-719.82, 21.45, 374.48]} rotation={[0, 1.55, 0]} scale={1.5}>
              <mesh geometry={nodes.Car_04_1_2_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-271.22, -14.73, -95.64]} rotation={[Math.PI / 2, 0, -0.22]} scale={1.5}>
              <mesh geometry={nodes.Car_08_2_World_ap11_0.geometry} material={materials['World_ap.11']} />
            </group>
            <group position={[81.42, 14.66, 401.83]} rotation={[-Math.PI, 1.56, Math.PI]} scale={1.5}>
              <mesh geometry={nodes.CAR_03_1_2_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-661.17, 8.75, 533.57]} rotation={[Math.PI, -1.43, Math.PI]} scale={1.5}>
              <mesh geometry={nodes.CAR_03_2_2_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[574.37, 21.45, -216.99]} rotation={[Math.PI, 1.36, -Math.PI]} scale={1.5}>
              <mesh geometry={nodes.Car_04_2_2_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-581.17, -14.73, -559.03]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={1.5}>
              <mesh geometry={nodes.Car_08_1_World_ap15_0.geometry} material={materials['World_ap.15']} />
            </group>
            <group position={[-6.17, -13.3, 785.62]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.5}>
              <mesh geometry={nodes.Car_08_World_ap16_0.geometry} material={materials['World_ap.16']} />
            </group>
            <group position={[565.85, -12.94, -425.91]} rotation={[Math.PI / 2, 0, -0.04]} scale={1.5}>
              <mesh geometry={nodes.Car_08_5_World_ap17_0.geometry} material={materials['World_ap.17']} />
            </group>
            <group position={[-932.32, 14.66, -406.06]} rotation={[0, -1.11, 0]} scale={1.5}>
              <mesh geometry={nodes.CAR_03_2_3_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-6.17, -13.3, 1020.42]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.5}>
              <mesh geometry={nodes.Car_08_6_World_ap19_0.geometry} material={materials['World_ap.19']} />
            </group>
            <group position={[940.97, 14.66, -243.45]} rotation={[0, 0.1, 0]} scale={1.5}>
              <mesh geometry={nodes.CAR_03_3_World_ap_0.geometry} material={materials.World_ap} />
            </group>
          </group>
          <group position={[-858.07, -53.78, 24.51]} rotation={[0, Math.PI / 2, 0]}>
            <group position={[-152.77, -44.68, -137.84]}>
              <group position={[474.6, 66.93, -256.18]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes.traffic_light_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[403.84, -14.34, 382.06]} rotation={[0, Math.PI / 2, 0]}>
                <mesh geometry={nodes.Light_3_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-82.28, -14.34, 382.06]} rotation={[0, Math.PI / 2, 0]}>
                <mesh geometry={nodes.Light_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[403.84, -14.34, -257.04]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes.Light_1_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-82.28, -14.34, -257.04]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes.Light_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-160.49, 66.93, -256.18]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes.traffic_light_1_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[474.6, 66.93, 379.61]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes.traffic_light_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
            </group>
            <group position={[1.9, -22.36, -74.24]}>
              <group position={[0, -2.84, 0]}>
                <mesh geometry={nodes.Floor_4_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[0, 2.84, 0]}>
                <mesh geometry={nodes.Floor_World_ap_0.geometry} material={materials.World_ap} />
              </group>
            </group>
            <group position={[-194.2, -41.07, -31.51]}>
              <group position={[3.14, -17.39, -42.03]} rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh geometry={nodes.Bed_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-1.05, 5.8, -183.5]} rotation={[-1.38, -1.4, -0.04]}>
                <mesh geometry={nodes.Bushes_3_World_ap_0.geometry} material={materials.World_ap} />
              </group>
            </group>
            <group position={[263.14, -41.07, -31.51]}>
              <group position={[3.14, -17.39, -42.03]} rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh geometry={nodes.Bed_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-1.05, 5.8, -183.5]} rotation={[-1.38, -1.4, -0.04]}>
                <mesh geometry={nodes.Bushes_3_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
            </group>
            <group position={[0, 104.5, 143.58]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.House_World_ap_0.geometry} material={materials.World_ap} />
            </group>
          </group>
          <group position={[84.72, -88.64, 8.45]}>
            <group position={[138.13, -19.65, 19.72]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Bench_1_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[131.58, -47.96, 121.88]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh geometry={nodes.House_2_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-201.53, -9.82, -54.04]}>
              <group position={[342.31, -14.34, 382.06]} rotation={[0, Math.PI / 2, 0]}>
                <mesh geometry={nodes.Light_3_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-82.28, -14.34, 382.06]} rotation={[0, Math.PI / 2, 0]}>
                <mesh geometry={nodes.Light_2_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[342.31, -14.34, -262.33]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes.Light_1_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-82.28, -14.34, -262.33]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes.Light_2_3_World_ap_0.geometry} material={materials.World_ap} />
              </group>
            </group>
            <group position={[-66.16, 12.5, 7.3]}>
              <group position={[0, -0.86, 0]}>
                <mesh geometry={nodes.Floor_4_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[0, 4.83, 0]}>
                <mesh geometry={nodes.Floor_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
            </group>
            <group position={[-73.05, -36.01, -229.55]} rotation={[0, -Math.PI / 2, 0]}>
              <group position={[-9.32, -17.96, 195.55]}>
                <mesh geometry={nodes.Firtree_47_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[8.99, 9.33, 112.14]}>
                <mesh geometry={nodes.Firtree_3_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[4.3, 1.08, 31.6]}>
                <mesh geometry={nodes.Firtree_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-9.61, -11.25, -45.05]}>
                <mesh geometry={nodes.Firtree_1_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-3.05, -11.96, -133.06]}>
                <mesh geometry={nodes.Firtree_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-19.84, 14, -8.48]}>
                <mesh geometry={nodes.Cube_7_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[8.21, -0.78, -227.08]} rotation={[0, 0.82, 0]}>
                <mesh geometry={nodes.Firtree_4_World_ap_0.geometry} material={materials.World_ap} />
              </group>
            </group>
            <group position={[138.13, -19.65, -109.7]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.Bench_World_ap_0.geometry} material={materials.World_ap} />
            </group>
          </group>
          <group position={[77.49, -88.64, -941.28]}>
            <group position={[111.52, 20.05, 89.05]}>
              <mesh geometry={nodes.Muff_1_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[111.52, 20.05, 188.91]}>
              <mesh geometry={nodes.Muff_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-201.53, -9.82, -54.04]}>
              <group position={[342.31, -14.34, 382.06]} rotation={[0, Math.PI / 2, 0]}>
                <mesh geometry={nodes.Light_3_3_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-82.28, -14.34, 382.06]} rotation={[0, Math.PI / 2, 0]}>
                <mesh geometry={nodes.Light_2_4_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[342.31, -14.34, -262.33]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes.Light_1_3_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-82.28, -14.34, -262.33]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes.Light_3_4_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[456.33, -14.34, 37.56]} rotation={[-Math.PI, 0, Math.PI]}>
                <mesh geometry={nodes.Light_4_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[456.33, -14.34, 1034.84]} rotation={[-Math.PI, 0, Math.PI]}>
                <mesh geometry={nodes.Light_5_World_ap_0.geometry} material={materials.World_ap} />
              </group>
            </group>
            <group position={[-66.16, 12.5, 7.3]}>
              <group position={[0, -0.86, 0]}>
                <mesh geometry={nodes.Floor_4_3_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[0, 4.83, 0]}>
                <mesh geometry={nodes.Floor_3_World_ap_0.geometry} material={materials.World_ap} />
              </group>
            </group>
            <group position={[-305.47, -36.01, 2.87]}>
              <group position={[-9.32, -17.96, 195.55]}>
                <mesh geometry={nodes.Firtree_47_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[8.99, 9.33, 112.14]}>
                <mesh geometry={nodes.Firtree_3_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[4.3, 1.08, 31.6]}>
                <mesh geometry={nodes.Firtree_2_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-9.61, -11.25, -45.05]}>
                <mesh geometry={nodes.Firtree_1_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-3.05, -11.96, -133.06]}>
                <mesh geometry={nodes.Firtree_2_3_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-18.9, 14, -1.58]}>
                <mesh geometry={nodes.Cube_7_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[8.21, -0.78, -227.08]} rotation={[0, 0.82, 0]}>
                <mesh geometry={nodes.Firtree_4_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
            </group>
            <group position={[-186.92, -19.65, -230.34]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Bench_2_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-186.92, -19.65, -152.01]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Behch_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-82.28, 5.96, -23.08]}>
              <mesh geometry={nodes.House_3_World_ap_0.geometry} material={materials.World_ap} />
            </group>
          </group>
          <group position={[-938.46, -88.64, -995.24]} rotation={[0, Math.PI / 2, 0]}>
            <group position={[-65.34, -36.63, -123.33]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Shop_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[46.26, -28.07, 47.98]} rotation={[Math.PI, 0, 0]}>
              <mesh geometry={nodes.Trash_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-82.16, -28.07, 47.98]} rotation={[Math.PI, 0, 0]}>
              <mesh geometry={nodes.Trash_2_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-201.53, -9.82, -54.04]}>
              <group position={[413.75, -15.93, 144.87]} rotation={[0, Math.PI / 2, 0]}>
                <mesh geometry={nodes.Light_3_5_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-134.68, -15.93, 145.28]} rotation={[0, Math.PI / 2, 0]}>
                <mesh geometry={nodes.Light_2_5_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[154.51, -15.93, -264.63]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes.Light_4_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
            </group>
            <group position={[-66.16, 12.5, 7.3]}>
              <group position={[0, 5.03, 0]}>
                <mesh geometry={nodes.Floor_4_4_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[70.76, 3.39, 277.5]}>
                <mesh geometry={nodes.Floor_4_5_World_ap_0.geometry} material={materials.World_ap} />
              </group>
            </group>
            <group position={[-356.01, -14.55, -70.98]} rotation={[Math.PI, 0, Math.PI]}>
              <group position={[2.86, -15.81, -38.21]} rotation={[-Math.PI, 0, Math.PI]}>
                <mesh geometry={nodes.Bed_3_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-0.95, 5.27, 177.88]} rotation={[-1.38, -1.4, -0.04]}>
                <mesh geometry={nodes.Bushes_15_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-0.95, 5.27, -52.62]} rotation={[-1.38, -1.4, -0.04]}>
                <mesh geometry={nodes.Bushes_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-0.95, 5.27, 49.3]} rotation={[-1.38, -1.4, -0.04]}>
                <mesh geometry={nodes.Bushes_2_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-20.42, -28.78, -82.21]} rotation={[-2.97, -0.12, -1.78]}>
                <mesh geometry={nodes.Tree_1_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-26.52, -46.04, 12.04]} rotation={[-1.38, -1.4, -0.04]}>
                <mesh geometry={nodes.Tree_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-39.24, -27.91, 158.02]} rotation={[-0.17, -0.16, 1.31]}>
                <mesh geometry={nodes.Tree_3_World_ap_0.geometry} material={materials.World_ap} />
              </group>
            </group>
            <group position={[180.93, -14.55, -70.98]} rotation={[Math.PI, 0, Math.PI]}>
              <group position={[2.86, -15.81, -38.21]} rotation={[-Math.PI, 0, Math.PI]}>
                <mesh geometry={nodes.Bed_4_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-0.95, 5.27, 177.88]} rotation={[-1.38, -1.4, -0.04]}>
                <mesh geometry={nodes.Bushes_15_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-0.95, 5.27, -52.62]} rotation={[-1.38, -1.4, -0.04]}>
                <mesh geometry={nodes.Bushes_2_3_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-0.95, 5.27, 49.3]} rotation={[-1.38, -1.4, -0.04]}>
                <mesh geometry={nodes.Bushes_4_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-20.42, -28.78, -82.21]} rotation={[-1.38, -1.4, -0.04]}>
                <mesh geometry={nodes.Tree_1_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-34.95, -27.91, 12.04]} rotation={[-1.38, -1.4, -0.04]}>
                <mesh geometry={nodes.Tree_2_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
              <group position={[-29.61, -27.91, 158.02]} rotation={[-0.17, -0.16, 1.31]}>
                <mesh geometry={nodes.Tree_3_2_World_ap_0.geometry} material={materials.World_ap} />
              </group>
            </group>
          </group>
          <group position={[-549.04, -127.66, -453.77]} rotation={[Math.PI / 2, 0, -Math.PI]}>
            <group position={[-878.59, -144.63, -92.94]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
              <mesh geometry={nodes.traffic_light_2_2_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-241.85, -144.63, -92.94]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
              <mesh geometry={nodes.traffic_light_1_2_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-878.59, 175.53, -92.94]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
              <mesh geometry={nodes.traffic_light_2_3_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <group position={[-106.28, -127.72, -0.4]}>
              <mesh geometry={nodes.ROAD_Lines_12_World_ap_0.geometry} material={materials.World_ap} />
            </group>
            <mesh geometry={nodes.ROAD_World_ap_0.geometry} material={materials.World_ap} />
          </group>
          <group position={[-434.04, -237.44, -451.91]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Floor_6_World_ap_0.geometry} material={materials.World_ap} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('small_city/scene.gltf')
